version: "3"
services:
  workspace:
    build:
      context: ./
    volumes:
      - ./:/app
    tty: true
    # depends_on:
    #   - ganache
    # networks:
    #   - brownietwork
  # ganache:
  #   image: trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"
  #   container_name: ganache
  #   networks:
  #     - brownietwork
# networks:
#   brownietwork:
#     driver: bridge
